version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9031:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: nextjs-app
